version: '3.8'

services:
  app:
    build: .
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment: 
            - DB_HOST=db
            - DB_NAME=testdb
            - DB_USER=postgres
            - DB_PASS=ss
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ss
    ports:
      - "5432:5432"
