# Generated by Django 3.2.12 on 2024-03-22 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title']},
        ),
    ]
