# Generated by Django 3.2.12 on 2024-03-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
